### ISSUE TITLE
Import issue on mac

### ISSUE THREAD

**Issue by adamgayoso** [chanzuckerberg/cellxgene-census#473]
## Describe the bug

I pip installed the package and am having trouble importing on mac os x.

<details>

```
Python 3.9.6 (default, Feb 26 2022, 11:21:57) 
[Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib
>>> importlib.import_module("cellxgene-census")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/adamgayoso/.pyenv/versions/3.9.6/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'cellxgene-census'
>>> importlib.import_module("cellxgene_census")
Traceback (most recent call last):
  File "/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/tiledbsoma/_tiledb_array.py", line 32, in _load_libs
    ctypes.CDLL(os.path.join(lib_dir, lib_name))
  File "/Users/adamgayoso/.pyenv/versions/3.9.6/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/tiledbsoma/libtiledbsoma.dylib, 0x0006): Library not loaded: @rpath/libtiledb.dylib
  Referenced from: <5E2BDA4A-FB32-3FE4-ABAD-A5E5EB950C12> /Users/adamgayoso/.pyenv/versions/3.9.6/envs/scvi-tools-dev/lib/python3.9/site-packages/tiledbsoma/libtiledbsoma.dylib
  Reason: tried: '/private/var/folders/1y/1rd4wh5x3hz548vp04mqdqy80000gn/T/pip-install-rifnmzqs/tiledbsoma_105a1cfda26541ee825061b0371e4730/dist_links/build/externals/install/lib/libtiledb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/1y/1rd4wh5x3hz548vp04mqdqy80000gn/T/pip-install-rifnmzqs/tiledbsoma_105a1cfda26541ee825061b0371e4730/dist_links/build/externals/install/lib/libtiledb.dylib' (no such file), '/private/var/folders/1y/1rd4wh5x3hz548vp04mqdqy80000gn/T/pip-install-rifnmzqs/tiledbsoma_105a1cfda26541ee825061b0371e4730/dist_links/dist/lib/libtiledb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/1y/1rd4wh5x3hz548vp04mqdqy80000gn/T/pip-install-rifnmzqs/tiledbsoma_105a1cfda26541ee825061b0371e4730/dist_links/dist/lib/libtiledb.dylib' (no such file), '/private/var/folders/1y/1rd4wh5x3hz548vp04mqdqy80000gn/T/pip-install-rifnmzqs/tiledbsoma_105a1cfda26541ee825061b0371e4730/dist_links/build/externals/install/lib/libtiledb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/1y/1rd4wh5x3hz548vp04mqdqy80000gn/T/pip-install-rifnmzqs/tiledbsoma_105a1cfda26541ee825061b0371e4730/dist_links/build/externals/install/lib/libtiledb.dylib' (no such file), '/private/var/folders/1y/1rd4wh5x3hz548vp04mqdqy80000gn/T/pip-install-rifnmzqs/tiledbsoma_105a1cfda26541ee825061b0371e4730/dist_links/dist/lib/libtiledb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/1y/1rd4wh5x3hz548vp04mqdqy80000gn/T/pip-install-rifnmzqs/tiledbsoma_105a1cfda26541ee825061b0371e4730/dist_links/dist/lib/libtiledb.dylib' (no such file), '/usr/local/lib/libtiledb.dylib' (no such file), '/usr/lib/libtiledb.dylib' (no such file, not in dyld cache)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/adamgayoso/.pyenv/versions/3.9.6/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/cellxgene_census/__init__.py", line 20, in <module>
    from ._get_anndata import get_anndata
  File "/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/cellxgene_census/_get_anndata.py", line 12, in <module>
    import tiledbsoma as soma
  File "/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/tiledbsoma/__init__.py", line 102, in <module>
    from ._collection import Collection
  File "/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/tiledbsoma/_collection.py", line 36, in <module>
    from ._common_nd_array import NDArray
  File "/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/tiledbsoma/_common_nd_array.py", line 18, in <module>
    from ._tiledb_array import TileDBArray
  File "/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/tiledbsoma/_tiledb_array.py", line 39, in <module>
    _load_libs()
  File "/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/tiledbsoma/_tiledb_array.py", line 35, in _load_libs
    ctypes.CDLL(lib_name)
  File "/Users/adamgayoso/.pyenv/versions/3.9.6/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libtiledbsoma.dylib, 0x0006): tried: 'libtiledbsoma.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibtiledbsoma.dylib' (no such file), '/usr/lib/libtiledbsoma.dylib' (no such file, not in dyld cache), 'libtiledbsoma.dylib' (no such file), '/usr/local/lib/libtiledbsoma.dylib' (no such file), '/usr/lib/libtiledbsoma.dylib' (no such file, not in dyld cache)
>>> import cellxgene_census
Traceback (most recent call last):
  File "/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/tiledbsoma/_tiledb_array.py", line 32, in _load_libs
    ctypes.CDLL(os.path.join(lib_dir, lib_name))
  File "/Users/adamgayoso/.pyenv/versions/3.9.6/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/tiledbsoma/libtiledbsoma.dylib, 0x0006): Library not loaded: @rpath/libtiledb.dylib
  Referenced from: <5E2BDA4A-FB32-3FE4-ABAD-A5E5EB950C12> /Users/adamgayoso/.pyenv/versions/3.9.6/envs/scvi-tools-dev/lib/python3.9/site-packages/tiledbsoma/libtiledbsoma.dylib
  Reason: tried: '/private/var/folders/1y/1rd4wh5x3hz548vp04mqdqy80000gn/T/pip-install-rifnmzqs/tiledbsoma_105a1cfda26541ee825061b0371e4730/dist_links/build/externals/install/lib/libtiledb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/1y/1rd4wh5x3hz548vp04mqdqy80000gn/T/pip-install-rifnmzqs/tiledbsoma_105a1cfda26541ee825061b0371e4730/dist_links/build/externals/install/lib/libtiledb.dylib' (no such file), '/private/var/folders/1y/1rd4wh5x3hz548vp04mqdqy80000gn/T/pip-install-rifnmzqs/tiledbsoma_105a1cfda26541ee825061b0371e4730/dist_links/dist/lib/libtiledb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/1y/1rd4wh5x3hz548vp04mqdqy80000gn/T/pip-install-rifnmzqs/tiledbsoma_105a1cfda26541ee825061b0371e4730/dist_links/dist/lib/libtiledb.dylib' (no such file), '/private/var/folders/1y/1rd4wh5x3hz548vp04mqdqy80000gn/T/pip-install-rifnmzqs/tiledbsoma_105a1cfda26541ee825061b0371e4730/dist_links/build/externals/install/lib/libtiledb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/1y/1rd4wh5x3hz548vp04mqdqy80000gn/T/pip-install-rifnmzqs/tiledbsoma_105a1cfda26541ee825061b0371e4730/dist_links/build/externals/install/lib/libtiledb.dylib' (no such file), '/private/var/folders/1y/1rd4wh5x3hz548vp04mqdqy80000gn/T/pip-install-rifnmzqs/tiledbsoma_105a1cfda26541ee825061b0371e4730/dist_links/dist/lib/libtiledb.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/1y/1rd4wh5x3hz548vp04mqdqy80000gn/T/pip-install-rifnmzqs/tiledbsoma_105a1cfda26541ee825061b0371e4730/dist_links/dist/lib/libtiledb.dylib' (no such file), '/usr/local/lib/libtiledb.dylib' (no such file), '/usr/lib/libtiledb.dylib' (no such file, not in dyld cache)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/cellxgene_census/__init__.py", line 20, in <module>
    from ._get_anndata import get_anndata
  File "/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/cellxgene_census/_get_anndata.py", line 12, in <module>
    import tiledbsoma as soma
  File "/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/tiledbsoma/__init__.py", line 102, in <module>
    from ._collection import Collection
  File "/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/tiledbsoma/_collection.py", line 36, in <module>
    from ._common_nd_array import NDArray
  File "/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/tiledbsoma/_common_nd_array.py", line 18, in <module>
    from ._tiledb_array import TileDBArray
  File "/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/tiledbsoma/_tiledb_array.py", line 39, in <module>
    _load_libs()
  File "/Users/adamgayoso/.pyenv/versions/scvi-tools-dev/lib/python3.9/site-packages/tiledbsoma/_tiledb_array.py", line 35, in _load_libs
    ctypes.CDLL(lib_name)
  File "/Users/adamgayoso/.pyenv/versions/3.9.6/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libtiledbsoma.dylib, 0x0006): tried: 'libtiledbsoma.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OSlibtiledbsoma.dylib' (no such file), '/usr/lib/libtiledbsoma.dylib' (no such file, not in dyld cache), 'libtiledbsoma.dylib' (no such file), '/usr/local/lib/libtiledbsoma.dylib' (no such file), '/usr/lib/libtiledbsoma.dylib' (no such file, not in dyld cache)
```

</details>

**Comment by slinnarsson** [comment]
Same here. Since the exception happens in tiledbsoma I suspect TileDb doesn't support Apple Silicon (I'm on an M2 MacBook Pro). Importing just tiledbsoma also doesn't work, with similar error. There is an [open issue](https://github.com/single-cell-data/TileDB-SOMA/issues/794) for tiledbsoma, which also mentions that TileDb itself also doesn't support Apple Silicon.

**Comment by pablo-gar** [comment]
This indeed seems to be a M1/M2 issue, and we may have already some work on this. I will notify our tiledbsoma partners.

Thanks for the flag!

**Comment by atolopko-czi** [comment]
A workaround for `pip` is to install `tiledbsoma` from source as follows:

```
python3 -m venv venv
. venv/bin/activate
pip install cellxgene-census

git clone https://github.com/single-cell-data/TileDB-SOMA.git /tmp/TileDB-SOMA
(cd /tmp/TileDB-SOMA && make install)
```

**Comment by pablo-gar** [comment]
@adamgayoso we are informed that this issue could be resolved by the comment above from Andrew or likely by using the tiledbsoma conda package.

Please let us know if that works for you and re-open this issue if it doesn't

**Comment by slinnarsson** [comment]
After installing tiledb from conda-forge, `import tiledb` works, but not `import tiledb-soma`. 

I don't know which condo tiledbsoma package you refer to @pablo-gar but I found only one, named tiledbsoma-py. However `conda install -c tiledb tiledbsoma-py` fails with 

```
UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - tiledbsoma-py -> python[version='>=3.10,<3.11.0a0|>=3.8,<3.9.0a0|>=3.8,<3.9.0a0|>=3.9,<3.10.0a0|>=3.9,<3.10.0a0',build=*_cpython]

Your python: python=3.9
```

I'm not familiar with conda versioning, but to me it seems that ">=3.9,<3.10a0" should work with 3.9. Maybe it's the `build=*_cpython` that doesn't match?

Installing tiled-soma from source instead, using `make install` fails with

```
$ make install
Building Release build
./scripts/bld: line 85: cmake: command not found
make: *** [install] Error 127
```

To install cmake, one should apparently [download a GUI-based Mac installer](https://cmake.org/install/), which adds a CMake app to the Applications folder; run that app and select a menu item `Tools->How to install for command line use`, copy one of the three different commands from the dialog that pops up, and run that in terminal (I chose to install symlink in /usr/bin, which worked). It's a weird approach, but ok.
 
After that, `make install` still fails, but this time it spits out several pages of compilation logs, sprinkled with a few errors like 

```
anaconda3/include/tiledb/config.h:52:32: error: 'iterator<std::forward_iterator_tag, const std::pair<std::string, std::string>>' is deprecated [-Werror,-Wdeprecated-declarations]
```

and ending with

```
make[5]: *** [src/CMakeFiles/TILEDB_SOMA_OBJECTS.dir/all] Error 2
make[5]: *** Waiting for unfinished jobs....
[ 94%] Built target Catch2
make[4]: *** [all] Error 2
make[3]: *** [libtiledbsoma-prefix/src/libtiledbsoma-stamp/libtiledbsoma-build] Error 2
make[2]: *** [CMakeFiles/libtiledbsoma.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [install] Error 2
```

So no, installing from source on a Mac with M1/M2 is not a solution.

I guess next thing to try would be a different Python version with the conda tiledbsoma-py  package, but I ran out of time and need to move on. I think a `pip install` package for Mac M1/M2 is still needed, or just state that Census doesn't support Mac.

**Comment by slinnarsson** [comment]
Sure, but to install Homebrew you need to [first install](https://docs.brew.sh/Installation) both `bash` and `Xcode`... and soon we will need a flowchart of all the different things that need to be installed in different ways and particular order. And either way, tiledbsoma didn't compile with cmake so it's a moot point.

**Comment by adamgayoso** [comment]
I think it would be great to reopen this issue as it really hasn't been solved and may help people in the future facing this issue.

**Comment by atolopko-czi** [comment]
Agreed, worth keeping open. Even after https://github.com/single-cell-data/TileDB-SOMA/issues/794 is fixed, it will take a new cellxgene-census release to incorporate it.

**Comment by pablo-gar** [comment]
@slinnarsson @adamgayoso 

We have prioritized this, pushed a change, and released in pypi. Would you mind trying again in fresh python environment?

```shell

# remove old env if needed
rm -rf venv

# install 
python -m venv ./venv
source ./venv/bin/activate

pip install -U cellxgene-census
```
